FROM node:16-alpine3.12

LABEL version="1.0"
LABEL description="Real Frontend For The Real Estate API"

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . .

CMD [ "npm", "run" , "start" ]